import { defineConfig } from 'vite'
import fs from 'fs'
import path from 'path'

function copyStaticFolders(folders) {
  return {
    name: 'copy-static-folders',
    closeBundle() {
      const rootDir = path.resolve(__dirname, 'src')
      const outDir = path.resolve(__dirname, 'dist')

      for (const folder of folders) {
        const source = path.join(rootDir, folder)
        const dest = path.join(outDir, folder)

        if (!fs.existsSync(source)) continue

        // Merge 'assets' to avoid removing files generated by Vite
        if (folder === 'assets' && fs.existsSync(dest)) {
          const children = fs.readdirSync(source)
          for (const child of children) {
            const sChild = path.join(source, child)
            const dChild = path.join(dest, child)
            fs.rmSync(dChild, { recursive: true, force: true })
            fs.cpSync(sChild, dChild, { recursive: true, force: true })
          }
        } else {
          fs.rmSync(dest, { recursive: true, force: true })
          fs.cpSync(source, dest, { recursive: true, force: true })
        }
      }

      const rootCss = path.join(rootDir, 'styles.css')
      const cssDest = path.join(outDir, 'styles.css')
      if (fs.existsSync(rootCss)) {
        fs.copyFileSync(rootCss, cssDest)
      }
    }
  }
}

export default defineConfig({
  root: 'src',
  base: './',
  build: {
    outDir: '../dist',
    emptyOutDir: true
  },
  plugins: [copyStaticFolders(['assets', 'data', 'css', 'components'])]
})